#!/usr/bin/env bash
# install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
sudo service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
