#!/usr/bin/env bash
# Install nginx --> engine x

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/deeshish.wachira.tech/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/deeshish.wachira.tech/html/index.html
sudo service nginx restart
