#!/usr/bin/env bash
# Install and configure nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Firewall setting: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Override the default index file served as home page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Redirect to /redirect_me to a youtube video
new_string="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
service nginx start
