#!/usr/bin/env bash
# Configure new nginx server to have a custom header
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "School" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
