#!/usr/bin/env bash
# displays "best school" 10 times but for the 9th iteration displays "hi" 

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
