#!/usr/bin/env bash
# displays numbers from 1 to 20 and:
# displays 4 and then bad luck from china for the 4th loop iteration.
# displays 9 and then bad luck from japan for the 9th loop iteration.
# displays 17 and then bad luck from italy for the 17th loop

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in 
		"4") echo "bad luck from china";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from italy";;
	esac
	(( count++ ))
done
